[package]
name = "zaino-testutils"
description = "Crate containing Zaino test specific functionality."
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
zaino-state = { workspace = true, features = ["bench"] }
zaino-testvectors.workspace = true
zaino-common.workspace = true

# Librustzcash
zcash_protocol = { workspace = true }
zcash_client_backend = { workspace = true, features = ["lightwalletd-tonic"] }

# Zingo-infra
zingo-infra-services = { workspace = true }

# ZingoLib
zingolib = { workspace = true }
testvectors = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "fmt",
    "env-filter",
    "time",
] }

# Miscellaneous
tokio = { workspace = true }
tonic = { workspace = true }
http = { workspace = true }
tempfile = { workspace = true }
portpicker = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
zingo-netutils = { workspace = true }
