# Configuration for Zaino

# Backend:

# Type of backend to use. Options are:
# - "fetch" - Uses JsonRPC client to fetch data (Zcashd, Zainod).
# - "state" - Uses ReadStateService to fetch data (Zebrad).
backend = "fetch"
#  ZebraDB location.
#  PathBuf, Required. Only used in state backend
# TODO: make it so this is only required when state backend is used
#  zebra_db_path = ""
#
#  Network chain type.
#  Required.
#  Network chain type (Mainnet, Testnet, Regtest).
network = "Testnet"

# Zainod JsonRPC server config:
# Optional: enables Zaino's JsonRPC server.
[json_server_settings]
  # JsonRPC server listen addr. Required if json_server_settings exists.
  json_rpc_listen_address = "127.0.0.1:8237"

  # Optional enables cookie-based authentication for JsonRPC server.
  # An empty value will have a default emphemeral path assigned to it when zaino loads the config.
  # (e.g., /tmp/zaino/.cookie or XDG_RUNTIME_DIR) will be used.
  # Directory to store authentication cookie file.
  # cookie_dir = ""
  # cookie_dir = "/path/to/cookie_dir"

# gRPC server config:
# Required for valid zainod config.
[grpc_settings]
# Zainod's gRPC server listen address.
  # SocketAddress, Required.
  grpc_listen_address = "127.0.0.1:8137"

  # Some Enables TLS for the gRPC server.
  # tls: Option<GrpcTls>,
  # [tls]
    # Path to the TLS certificate file in PEM format.
    # cert_path: ""
    # cert_path = "/path/to/cert.pem"
    # Path to the TLS private key file in PEM format.
    # key_path = ""
    # key_path = "/path/to/key.pem"

# Validator config:
# Required for valid zainod config.
[validator_settings]
  # Full node / validator gRPC listen address (Zebra only).
  #
  # Must be a "private" address as defined in [IETF RFC 1918] for IPv4 or [IETF RFC 4193] for IPv6.
  # Cookie or user/password authentication is recommended for non-localhost addresses.
  validator_grpc_listen_address = "127.0.0.1:18232"

  # SocketAddr, Required.
  validator_jsonrpc_listen_address = "127.0.0.1:18230"

    # Optional. Enable validator rpc cookie authentication with Some.
    # Path to the validator cookie file.
    # validator_cookie_path = "/path/to/validator.cookie"
    # validator_cookie_path = ""
    # Optional. Enable  user / pass authentication with Some.
    # Full node / validator Username.
    # validator_user = ""
    # Optional. Enable user / pass authentication with Some
    # full node / validator Password.
    # validator_password: ""
    #
#  Service-level configuration (timeout, channel size).
#  Required.
# 
#  [service]
  # RPC service timeout (in seconds) 
  # timeout
  # RPC maximum channel (queue) size
  # channel_size

#  Storage configuration (cache and database).
#  Required.
#
# Database config (required)
# [storage.database]
## the location of zaino's database file
# path = ""
## the database size limit, in GB (defaults to 128)
# size = 128
# 
# Cache config. Optional, primarily for developer use
#  [storage.cache]
## capacity of the DashMaps used for caching
# capacity = 10000
## how large the shards the dash map is split into,
## in powers of 2
# shard_power = 4  

