#!/usr/bin/env bash
set -eo pipefail

# --- Configuration & Defaults ---
# Essential global defaults
: "${ZAINO_CONF_PATH:=${HOME}/.config/zaino/zindexer.toml}"
: "${ZAINO_DATA_DIR:=${HOME}/.cache/zaino}" # For zaino_db_path if not specified directly
: "${ZEBRA_DATA_DIR:=${HOME}/.cache/zebra}" # For zebra_db_path if not specified directly
: "${RUST_LOG:=info}"

# Backend
: "${ZAINO_BACKEND:=fetch}" # "fetch" or "state"

# Zaino JSON-RPC Server
: "${ZAINO_JSON_RPC_ENABLE:=false}"
: "${ZAINO_JSON_RPC_LISTEN_ADDRESS:=localhost:8237}"
: "${ZAINO_JSON_RPC_COOKIE_AUTH_ENABLE:=false}"
: "${ZAINO_JSON_RPC_COOKIE_DIR:=${ZAINO_DATA_DIR}/rpc-cookies}" # Default cookie dir for zaino's rpc

# Zaino gRPC Server
: "${ZAINO_GRPC_LISTEN_ADDRESS:=localhost:8137}"
: "${ZAINO_GRPC_TLS_ENABLE:=false}"
: "${ZAINO_GRPC_TLS_CERT_PATH:=None}"
: "${ZAINO_GRPC_TLS_KEY_PATH:=None}"

# Validator (e.g., Zebrad) JSON-RPC Client Config
: "${ZAINO_VALIDATOR_LISTEN_ADDRESS:=localhost:18232}" # Default Zebra RPC
: "${ZAINO_VALIDATOR_COOKIE_AUTH_ENABLE:=false}"
: "${ZAINO_VALIDATOR_COOKIE_PATH:=${ZEBRA_DATA_DIR}/.cookie}" # Default Zebra cookie path
: "${ZAINO_VALIDATOR_USER:=}"
: "${ZAINO_VALIDATOR_PASSWORD:=}"

# Storage/Cache
: "${ZAINO_MAP_CAPACITY:=None}"
: "${ZAINO_MAP_SHARD_AMOUNT:=None}"
: "${ZAINO_DB_PATH:=${ZAINO_DATA_DIR}/zaino_db}"
: "${ZEBRA_DB_PATH:=${ZEBRA_DATA_DIR}/db}" # Common path for zebra's state
: "${ZAINO_DB_SIZE:=None}"

# Network
: "${ZAINO_NETWORK:=Testnet}" # Mainnet, Testnet, Regtest

# Options
: "${ZAINO_NO_SYNC:=false}"
: "${ZAINO_NO_DB:=false}"
: "${ZAINO_SLOW_SYNC:=false}"


# --- Helper Functions ---

# Ensures a directory exists and is owned by UID:GID if running as root.
ensure_dir_owned() {
    local dir_path="$1"
    if [[ ! -d "${dir_path}" ]]; then
        mkdir -p "${dir_path}" || { echo "ERROR: Failed to create directory: ${dir_path}"; exit 1; }
    fi
    if [[ "$(id -u)" == "0" ]]; then
        if ! chown -R "${UID}:${GID}" "${dir_path}" >/dev/null 2>&1; then
            echo "WARNING: Failed to set recursive ownership (chown -R ${UID}:${GID}) for directory '${dir_path}'." >&2
            echo "         This could be due to read-only mounts or other permission issues." >&2
            echo "         The application may proceed, but could misbehave or fail to start correctly if permissions are insufficient." >&2
            # As a fallback, try to chown only the directory itself, not recursively.
            if ! chown "${UID}:${GID}" "${dir_path}" >/dev/null 2>&1; then
                echo "WARNING: Failed to set ownership (chown ${UID}:${GID}) for the directory '${dir_path}' itself." >&2
            else
                echo "INFO: Successfully set ownership (chown ${UID}:${GID}) for the directory '${dir_path}' itself (non-recursive)." >&2
            fi
        fi
    fi
}

# Formats a value for a TOML string field.
# If the input value is the literal string "None" or empty, it outputs the TOML string "\"None\"".
# Otherwise, it outputs the input value, quoted for TOML.
format_toml_string_field() {
    local input_val="${1}"
    if [[ "${input_val}" == "None" || -z "${input_val}" ]]; then
        echo "\"None\""
    else
        echo "\"${input_val}\""
    fi
}

# Generates zindexer.toml from environment variables if it doesn't exist.
generate_config_if_needed() {
  if [[ -f "${ZAINO_CONF_PATH}" && -r "${ZAINO_CONF_PATH}" ]]; then
    echo "INFO: Using existing Zaino config file: ${ZAINO_CONF_PATH}"
    return
  fi

  echo "INFO: Generating Zaino config at ${ZAINO_CONF_PATH} from environment variables..."
  ensure_dir_owned "$(dirname "${ZAINO_CONF_PATH}")"

  # Define defaults directly here or use them inline with ":-"
  local default_json_rpc_cookie_dir="${ZAINO_DATA_DIR}/rpc-cookies"
  local default_validator_cookie_path="${ZEBRA_DATA_DIR}/.cookie"
  local default_zaino_db_path="${ZAINO_DATA_DIR}/zaino_db"
  local default_zebra_db_path="${ZEBRA_DATA_DIR}/db"

  cat >"${ZAINO_CONF_PATH}" <<EOF
# Auto-generated by entrypoint.sh for Zaino

backend = "${ZAINO_BACKEND:-fetch}"

# JsonRPC server config
enable_json_server = ${ZAINO_JSON_RPC_ENABLE:-false}
json_rpc_listen_address = "${ZAINO_JSON_RPC_LISTEN_ADDRESS:-0.0.0.0:8237}"
enable_cookie_auth = ${ZAINO_JSON_RPC_COOKIE_AUTH_ENABLE:-false}
cookie_dir = $(format_toml_string_field "${ZAINO_JSON_RPC_COOKIE_DIR:-${default_json_rpc_cookie_dir}}")

# gRPC server config
grpc_listen_address = "${ZAINO_GRPC_LISTEN_ADDRESS:-localhost:8137}"
grpc_tls = ${ZAINO_GRPC_TLS_ENABLE:-false}
tls_cert_path = $(format_toml_string_field "${ZAINO_GRPC_TLS_CERT_PATH:-None}")
tls_key_path = $(format_toml_string_field "${ZAINO_GRPC_TLS_KEY_PATH:-None}")

# JsonRPC client config (validator)
validator_listen_address = "${ZAINO_VALIDATOR_LISTEN_ADDRESS:-localhost:18232}"
validator_cookie_auth = ${ZAINO_VALIDATOR_COOKIE_AUTH_ENABLE:-false}
validator_cookie_path = $(format_toml_string_field "${ZAINO_VALIDATOR_COOKIE_PATH:-${default_validator_cookie_path}}")
if [[ "${ZAINO_VALIDATOR_COOKIE_AUTH_ENABLE:-false}" == "false" ]]; then
  # Only add user/pass to TOML if cookie auth is explicitly disabled
  ${ZAINO_VALIDATOR_USER:+"validator_user = \"${ZAINO_VALIDATOR_USER}\""}
  ${ZAINO_VALIDATOR_PASSWORD:+"validator_password = \"${ZAINO_VALIDATOR_PASSWORD}\""}
fi

# Mempool, Non-Finalised State and Finalised State config
map_capacity = $(format_toml_string_field "${ZAINO_MAP_CAPACITY:-None}")
map_shard_amount = $(format_toml_string_field "${ZAINO_MAP_SHARD_AMOUNT:-None}")
zaino_db_path = $(format_toml_string_field "${ZAINO_DB_PATH:-${default_zaino_db_path}}")
zebra_db_path = $(format_toml_string_field "${ZEBRA_DB_PATH:-${default_zebra_db_path}}")
db_size = $(format_toml_string_field "${ZAINO_DB_SIZE:-None}")

# Network
network = "${ZAINO_NETWORK:-Testnet}"

# Options
no_sync = ${ZAINO_NO_SYNC:-false}
no_db = ${ZAINO_NO_DB:-false}
slow_sync = ${ZAINO_SLOW_SYNC:-false}
EOF

  if [[ "$(id -u)" == "0" ]]; then
      chown "${UID}:${GID}" "${ZAINO_CONF_PATH}"
  fi
}

# --- Main Execution ---

# 1. Ensure essential directories exist and have correct ownership
ensure_dir_owned "${ZAINO_DATA_DIR}"
ensure_dir_owned "$(dirname "${ZAINO_CONF_PATH}")"

# Ensure optional directories are created if their paths are set (and not "None")

json_rpc_cookie_dir_val="${ZAINO_JSON_RPC_COOKIE_DIR:-${ZAINO_DATA_DIR}/rpc-cookies}"
if [[ "${json_rpc_cookie_dir_val}" != "None" && -n "${json_rpc_cookie_dir_val}" ]]; then
    ensure_dir_owned "${json_rpc_cookie_dir_val}"
fi

validator_cookie_path_val="${ZAINO_VALIDATOR_COOKIE_PATH:-${ZEBRA_DATA_DIR}/.cookie}"
if [[ "${validator_cookie_path_val}" != "None" && -n "${validator_cookie_path_val}" ]]; then
    ensure_dir_owned "$(dirname "${validator_cookie_path_val}")"
fi

zaino_db_path_val="${ZAINO_DB_PATH:-${ZAINO_DATA_DIR}/zaino_db}"
if [[ "${zaino_db_path_val}" != "None" && -n "${zaino_db_path_val}" ]]; then
    ensure_dir_owned "$(dirname "${zaino_db_path_val}")"
fi

zebra_db_path_val="${ZEBRA_DB_PATH:-${ZEBRA_DATA_DIR}/db}"
if [[ "${zebra_db_path_val}" != "None" && -n "${zebra_db_path_val}" ]]; then
    ensure_dir_owned "$(dirname "${zebra_db_path_val}")"
fi

# 2. Generate config file if it doesn't exist
generate_config_if_needed

echo "INFO: Contents of Zaino config file at ${ZAINO_CONF_PATH}:"
cat "${ZAINO_CONF_PATH}"
echo "--- End of Zaino config file ---"

# 3. Display logging information
echo "INFO: Using Rust log level: ${RUST_LOG}"
echo "      To change log level, set RUST_LOG (e.g., RUST_LOG=debug,zainod=trace)"

# 4. Determine command to run
final_cmd=()
if [[ $# -eq 0 || "$1" == "zainod" || "$1" == -* ]]; then
    declare -a zaino_args=()
    if [[ "$1" == "zainod" ]]; then
        zaino_args=("${@:2}")
    else
        zaino_args=("$@")
    fi
    final_cmd=("zainod" "--config" "${ZAINO_CONF_PATH}" "${zaino_args[@]}")
else
    final_cmd=("$@")
fi

# 5. Execute command as the target user
echo "INFO: Executing: gosu ${USER} ${final_cmd[*]}"
export RUST_LOG
exec gosu "${USER}" "${final_cmd[@]}"
