//! Proc-macros for `zaino-persistence-codec`.
//!
//! [`macro@PersistentRecord`] derives the mechanical *record ⇄ on-disk bytes*
//! serde — the `RecordLayout` half of a DTO's `PersistentRecord`. For a struct
//! whose fields are layout atoms in declaration order, that half is one
//! `LayoutAtom::encode` call per field on encode and one `LayoutAtom::decode`
//! read per field on decode — pure boilerplate the compiler can write. The
//! per-type byte logic lives in the `LayoutAtom` trait in
//! `zaino_persistence_codec::layout`, not in this macro, so the derive is just
//! field iteration and both sides are generated from the same field list — they
//! cannot drift. The domain-crossing half (`from_domain`/`into_domain`) stays
//! hand-written, because it is where validation and domain mapping live.
//!
//! A record whose framing is irregular (an unframed repetition, a count-prefixed
//! nested collection) is not expressible as one call per field; it implements
//! `RecordLayout` by hand instead of deriving.
//!
//! (`RecordLayout`, `PersistentRecord`, `LayoutAtom`, `Writer`, `Cursor`, and
//! `DecodeError` all live in the `zaino_persistence_codec` crate, which this
//! proc-macro crate does not depend on — hence the plain names rather than
//! links.)

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{parse_macro_input, spanned::Spanned, Attribute, Data, DeriveInput, Fields, Index, Type};

/// Derive the `RecordLayout` half of a `PersistentRecord`: the mechanical
/// `encode`/`decode` that maps a DTO struct to and from its on-disk bytes.
///
/// One `LayoutAtom` call per field in declaration order, so the generated bytes
/// are exactly the field layout. A field's type must implement
/// `zaino_persistence_codec::layout::LayoutAtom` — the supported atoms are:
///
/// - `u8` — a single byte.
/// - `u32` / `u64` — little-endian; `#[persistent(be)]` selects big-endian (the
///   key-ordering case), routing through the `BeU32`/`BeU64` atoms.
/// - `[u8; N]` for any `N` — `N` raw bytes (this covers the 32-byte
///   hash/commitment width).
/// - `Vec<u8>` — a length-prefixed byte run.
///
/// The reverse reads the same atoms in order and rejects a trailing tail, so a
/// short or over-long buffer fails with a `DecodeError` rather than a panic.
///
/// This derive does **not** touch `type Domain`, `from_domain`, or
/// `into_domain` — those stay hand-written on the `PersistentRecord` impl, where
/// the domain mapping and disk→domain validation live.
#[proc_macro_derive(PersistentRecord, attributes(persistent))]
pub fn derive_persistent_record(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match expand(&input) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.to_compile_error().into(),
    }
}

fn expand(input: &DeriveInput) -> syn::Result<proc_macro2::TokenStream> {
    let ident = &input.ident;

    if !input.generics.params.is_empty() {
        return Err(syn::Error::new(
            input.generics.params.span(),
            "#[derive(PersistentRecord)] does not support generic types; \
             implement RecordLayout by hand",
        ));
    }

    let fields = match &input.data {
        Data::Struct(data) => &data.fields,
        Data::Enum(data) => {
            return Err(syn::Error::new(
                data.enum_token.span,
                "#[derive(PersistentRecord)] supports only structs",
            ))
        }
        Data::Union(data) => {
            return Err(syn::Error::new(
                data.union_token.span,
                "#[derive(PersistentRecord)] supports only structs",
            ))
        }
    };

    let (encodes, decodes, ctor) = match fields {
        Fields::Named(named) => {
            let mut encodes = Vec::new();
            let mut decodes = Vec::new();
            let mut binds = Vec::new();
            for field in &named.named {
                let be = parse_be(&field.attrs)?;
                let name = field
                    .ident
                    .clone()
                    .ok_or_else(|| syn::Error::new(field.span(), "named field without ident"))?;
                let access = quote! { self.#name };
                let (encode, decode) = field_codec(&field.ty, be, &access, &name)?;
                encodes.push(encode);
                decodes.push(decode);
                binds.push(name);
            }
            (encodes, decodes, quote! { Self { #(#binds),* } })
        }
        Fields::Unnamed(unnamed) => {
            let mut encodes = Vec::new();
            let mut decodes = Vec::new();
            let mut binds = Vec::new();
            for (i, field) in unnamed.unnamed.iter().enumerate() {
                let be = parse_be(&field.attrs)?;
                let index = Index::from(i);
                let access = quote! { self.#index };
                let bind = format_ident!("field{}", i);
                let (encode, decode) = field_codec(&field.ty, be, &access, &bind)?;
                encodes.push(encode);
                decodes.push(decode);
                binds.push(bind);
            }
            (encodes, decodes, quote! { Self(#(#binds),*) })
        }
        Fields::Unit => {
            return Err(syn::Error::new(
                ident.span(),
                "#[derive(PersistentRecord)] needs fields to encode; a unit struct has none",
            ))
        }
    };

    Ok(quote! {
        impl ::zaino_persistence_codec::RecordLayout for #ident {
            fn encode(&self) -> ::std::vec::Vec<u8> {
                let mut writer = ::zaino_persistence_codec::layout::Writer::new();
                #(#encodes)*
                writer.into_bytes()
            }

            fn decode(
                bytes: &[u8],
            ) -> ::core::result::Result<Self, ::zaino_persistence_codec::DecodeError> {
                let mut cursor = ::zaino_persistence_codec::layout::Cursor::new(bytes);
                #(#decodes)*
                cursor.finish()?;
                ::core::result::Result::Ok(#ctor)
            }
        }
    })
}

/// The encode statement and decode `let` binding for one field. A plain field
/// dispatches generically to its type's `LayoutAtom`; a `#[persistent(be)]`
/// field routes through the `BeU32`/`BeU64` big-endian atom for its width. The
/// per-type byte logic is entirely in the `LayoutAtom` impls — this only picks
/// which atom applies.
///
/// `access` is the field's read expression (`self.name` / `self.0`); `bind` is
/// the local the decode reads into.
fn field_codec(
    ty: &Type,
    be: bool,
    access: &proc_macro2::TokenStream,
    bind: &syn::Ident,
) -> syn::Result<(proc_macro2::TokenStream, proc_macro2::TokenStream)> {
    let layout = quote! { ::zaino_persistence_codec::layout };

    if be {
        let wrapper = match primitive_name(ty).as_deref() {
            Some("u32") => quote! { #layout::BeU32 },
            Some("u64") => quote! { #layout::BeU64 },
            _ => {
                return Err(syn::Error::new(
                    ty.span(),
                    "#[persistent(be)] applies only to u32/u64",
                ))
            }
        };
        return Ok((
            quote! { <#wrapper as #layout::LayoutAtom>::encode(&#wrapper(#access), &mut writer); },
            quote! { let #bind = <#wrapper as #layout::LayoutAtom>::decode(&mut cursor)?.0; },
        ));
    }

    Ok((
        quote! { <#ty as #layout::LayoutAtom>::encode(&#access, &mut writer); },
        quote! { let #bind = <#ty as #layout::LayoutAtom>::decode(&mut cursor)?; },
    ))
}

/// The identifier of a bare, unparameterised path type (`u8`, `u32`, `u64`).
/// Returns `None` for arrays, generics, references, or paths carrying arguments.
/// Used only to pick the big-endian atom for a `#[persistent(be)]` field.
fn primitive_name(ty: &Type) -> Option<String> {
    let Type::Path(path) = ty else { return None };
    if path.qself.is_some() {
        return None;
    }
    let segment = path.path.segments.last()?;
    if segment.arguments.is_empty() {
        Some(segment.ident.to_string())
    } else {
        None
    }
}

/// Read the `#[persistent(be)]` flag off a field. `be` is the only recognised
/// option; anything else is a compile error naming it.
fn parse_be(attrs: &[Attribute]) -> syn::Result<bool> {
    let mut be = false;
    for attr in attrs {
        if attr.path().is_ident("persistent") {
            attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("be") {
                    be = true;
                    Ok(())
                } else {
                    Err(meta.error("unknown #[persistent(...)] option; expected `be`"))
                }
            })?;
        }
    }
    Ok(be)
}
