//! Proc-macros for `zaino-persistence-codec`.
//!
//! [`macro@PersistentRecord`] derives the mechanical *record ⇄ on-disk bytes*
//! serde — the `RecordLayout` half of a DTO's `PersistentRecord`. For a struct
//! whose fields are layout atoms in declaration order, that half is one `Writer`
//! call per field on encode and one `Cursor` read per field on decode — pure
//! boilerplate the compiler can write. The domain-crossing half
//! (`from_domain`/`into_domain`) stays hand-written, because it is where
//! validation and domain mapping live.
//!
//! A record whose framing is irregular (an unframed repetition, a count-prefixed
//! nested collection) is not expressible as one call per field; it implements
//! `RecordLayout` by hand instead of deriving.
//!
//! (`RecordLayout`, `PersistentRecord`, `Writer`, `Cursor`, and `DecodeError`
//! all live in the `zaino_persistence_codec` crate, which this proc-macro crate
//! does not depend on — hence the plain names rather than links.)

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{
    parse_macro_input, spanned::Spanned, Attribute, Data, DeriveInput, Expr, ExprLit, Fields,
    GenericArgument, Index, Lit, PathArguments, Type, TypeArray,
};

/// Derive the `RecordLayout` half of a `PersistentRecord`: the mechanical
/// `encode`/`decode` that maps a DTO struct to and from its on-disk bytes.
///
/// One call per field in declaration order, so the generated bytes are exactly
/// the field layout. Supported field types:
///
/// - `u8` — a single byte.
/// - `u32` / `u64` — little-endian by default; `#[persistent(be)]` selects
///   big-endian (the key-ordering case).
/// - `[u8; 32]` — the 32-byte hash/commitment width, via `bytes32`.
/// - `[u8; N]` for any other `N` — `N` raw bytes.
/// - `Vec<u8>` — a length-prefixed byte run.
///
/// The reverse reads the same atoms in order and rejects a trailing tail, so a
/// short or over-long buffer fails with a `DecodeError` rather than a panic.
///
/// This derive does **not** touch `type Domain`, `from_domain`, or
/// `into_domain`; those remain a hand-written `impl PersistentRecord`.
///
/// # Field attributes
///
/// - `#[persistent(be)]` — encode a `u32`/`u64` field big-endian. Used where an
///   on-disk key must sort in numeric order under byte-lexicographic comparison.
///
/// # Unsupported shapes
///
/// Enums, unions, unit structs, generic types, and any field type outside the
/// list above are rejected with a compile error naming the offending shape;
/// implement `RecordLayout` by hand for those.
#[proc_macro_derive(PersistentRecord, attributes(persistent))]
pub fn derive_persistent_record(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match expand(&input) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.to_compile_error().into(),
    }
}

fn expand(input: &DeriveInput) -> syn::Result<proc_macro2::TokenStream> {
    let ident = &input.ident;

    if !input.generics.params.is_empty() {
        return Err(syn::Error::new(
            input.generics.params.span(),
            "#[derive(PersistentRecord)] does not support generic types; \
             implement RecordLayout by hand",
        ));
    }

    let fields = match &input.data {
        Data::Struct(data) => &data.fields,
        Data::Enum(data) => {
            return Err(syn::Error::new(
                data.enum_token.span,
                "#[derive(PersistentRecord)] supports only structs",
            ))
        }
        Data::Union(data) => {
            return Err(syn::Error::new(
                data.union_token.span,
                "#[derive(PersistentRecord)] supports only structs",
            ))
        }
    };

    let (encodes, decodes, ctor) = match fields {
        Fields::Named(named) => {
            let mut encodes = Vec::new();
            let mut decodes = Vec::new();
            let mut binds = Vec::new();
            for field in &named.named {
                let be = parse_be(&field.attrs)?;
                let name = field
                    .ident
                    .clone()
                    .ok_or_else(|| syn::Error::new(field.span(), "named field without ident"))?;
                let access = quote! { self.#name };
                let (encode, decode) = field_codec(&field.ty, be, &access, &name)?;
                encodes.push(encode);
                decodes.push(decode);
                binds.push(name);
            }
            (encodes, decodes, quote! { Self { #(#binds),* } })
        }
        Fields::Unnamed(unnamed) => {
            let mut encodes = Vec::new();
            let mut decodes = Vec::new();
            let mut binds = Vec::new();
            for (i, field) in unnamed.unnamed.iter().enumerate() {
                let be = parse_be(&field.attrs)?;
                let index = Index::from(i);
                let access = quote! { self.#index };
                let bind = format_ident!("field{}", i);
                let (encode, decode) = field_codec(&field.ty, be, &access, &bind)?;
                encodes.push(encode);
                decodes.push(decode);
                binds.push(bind);
            }
            (encodes, decodes, quote! { Self(#(#binds),*) })
        }
        Fields::Unit => {
            return Err(syn::Error::new(
                ident.span(),
                "#[derive(PersistentRecord)] needs fields to encode; a unit struct has none",
            ))
        }
    };

    Ok(quote! {
        impl ::zaino_persistence_codec::RecordLayout for #ident {
            fn encode(&self) -> ::std::vec::Vec<u8> {
                let mut writer = ::zaino_persistence_codec::layout::Writer::new();
                #(#encodes)*
                writer.into_bytes()
            }

            fn decode(
                bytes: &[u8],
            ) -> ::core::result::Result<Self, ::zaino_persistence_codec::DecodeError> {
                let mut cursor = ::zaino_persistence_codec::layout::Cursor::new(bytes);
                #(#decodes)*
                cursor.finish()?;
                ::core::result::Result::Ok(#ctor)
            }
        }
    })
}

/// The encode statement and decode `let` binding for one field, chosen by its
/// type and the `be` attribute. `access` is the field's read expression
/// (`self.name` / `self.0`); `bind` is the local the decode reads into.
fn field_codec(
    ty: &Type,
    be: bool,
    access: &proc_macro2::TokenStream,
    bind: &syn::Ident,
) -> syn::Result<(proc_macro2::TokenStream, proc_macro2::TokenStream)> {
    if let Some(name) = primitive_name(ty) {
        match name.as_str() {
            "u8" => {
                reject_be(be, ty, "u8")?;
                return Ok((
                    quote! { writer.raw(&[#access]); },
                    quote! { let #bind = cursor.array::<1>()?[0]; },
                ));
            }
            "u32" => {
                return Ok(int_codec(
                    access,
                    bind,
                    be,
                    4,
                    quote! { u32 },
                    quote! { u32 },
                ))
            }
            "u64" => {
                return Ok(int_codec(
                    access,
                    bind,
                    be,
                    8,
                    quote! { u64 },
                    quote! { u64 },
                ))
            }
            _ => {}
        }
    }

    if let Type::Array(array) = ty {
        if array_elem_is_u8(array) {
            reject_be(be, ty, "a byte array")?;
            let len = &array.len;
            if array_len_is(len, 32) {
                return Ok((
                    quote! { writer.bytes32(&#access); },
                    quote! { let #bind = cursor.bytes32()?; },
                ));
            }
            return Ok((
                quote! { writer.raw(&#access); },
                quote! { let #bind = cursor.array::<#len>()?; },
            ));
        }
    }

    if is_vec_u8(ty) {
        reject_be(be, ty, "Vec<u8>")?;
        return Ok((
            quote! { writer.len_prefixed(&#access); },
            quote! { let #bind = cursor.len_prefixed()?; },
        ));
    }

    Err(syn::Error::new(
        ty.span(),
        "unsupported field type for #[derive(PersistentRecord)]: expected u8, u32, u64, \
         [u8; N], or Vec<u8>; records with irregular framing implement RecordLayout by hand",
    ))
}

/// The encode/decode for a `u32`/`u64` field. Little-endian goes through the
/// `Writer`/`Cursor` integer atoms; big-endian frames the bytes directly, as the
/// layout atoms are little-endian only.
fn int_codec(
    access: &proc_macro2::TokenStream,
    bind: &syn::Ident,
    be: bool,
    width: usize,
    le_method: proc_macro2::TokenStream,
    int_ty: proc_macro2::TokenStream,
) -> (proc_macro2::TokenStream, proc_macro2::TokenStream) {
    if be {
        let width = Index::from(width);
        (
            quote! { writer.raw(&#access.to_be_bytes()); },
            quote! { let #bind = #int_ty::from_be_bytes(cursor.array::<#width>()?); },
        )
    } else {
        (
            quote! { writer.#le_method(#access); },
            quote! { let #bind = cursor.#le_method()?; },
        )
    }
}

/// Reject `#[persistent(be)]` on a field where endianness is meaningless.
fn reject_be(be: bool, ty: &Type, what: &str) -> syn::Result<()> {
    if be {
        return Err(syn::Error::new(
            ty.span(),
            format!("#[persistent(be)] applies only to u32/u64, not {what}"),
        ));
    }
    Ok(())
}

/// The identifier of a bare, unparameterised path type (`u8`, `u32`, `u64`).
/// Returns `None` for arrays, generics, references, or paths carrying arguments.
fn primitive_name(ty: &Type) -> Option<String> {
    let Type::Path(path) = ty else { return None };
    if path.qself.is_some() {
        return None;
    }
    let segment = path.path.segments.last()?;
    if segment.arguments.is_empty() {
        Some(segment.ident.to_string())
    } else {
        None
    }
}

/// Whether an array type's element is `u8`.
fn array_elem_is_u8(array: &TypeArray) -> bool {
    primitive_name(&array.elem).as_deref() == Some("u8")
}

/// Whether an array-length expression is the integer literal `n`.
fn array_len_is(len: &Expr, n: usize) -> bool {
    let Expr::Lit(ExprLit {
        lit: Lit::Int(int), ..
    }) = len
    else {
        return false;
    };
    int.base10_parse::<usize>().map(|v| v == n).unwrap_or(false)
}

/// Whether a type is exactly `Vec<u8>`.
fn is_vec_u8(ty: &Type) -> bool {
    let Type::Path(path) = ty else { return false };
    let Some(segment) = path.path.segments.last() else {
        return false;
    };
    if segment.ident != "Vec" {
        return false;
    }
    let PathArguments::AngleBracketed(args) = &segment.arguments else {
        return false;
    };
    match args.args.first() {
        Some(GenericArgument::Type(inner)) => primitive_name(inner).as_deref() == Some("u8"),
        _ => false,
    }
}

/// Read the `#[persistent(be)]` flag off a field. `be` is the only recognised
/// option; anything else is a compile error naming it.
fn parse_be(attrs: &[Attribute]) -> syn::Result<bool> {
    let mut be = false;
    for attr in attrs {
        if attr.path().is_ident("persistent") {
            attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("be") {
                    be = true;
                    Ok(())
                } else {
                    Err(meta.error("unknown #[persistent(...)] option; expected `be`"))
                }
            })?;
        }
    }
    Ok(be)
}
