[package]
name = "core2"
version = "0.3.3"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"
description = "Compatibility shim that satisfies legacy core2 dependencies using corez."

[features]
default = ["std"]
alloc = ["corez/alloc"]
std = ["alloc", "corez/std"]
nightly = []

[dependencies]
corez = { version = "0.1.1", default-features = false }
