[profile.default]
test-threads = 6
fail-fast = false
# retries = 1

# All the following tests keep failing because of zebra with the following error message:
# "Serialization/Deserialization Error: data did not match any variant of untagged enum Input at line 1 column <X>"
# We will ignore these tests for now in CI, until zebra releases the fix

[profile.ci]
default-filter = """
    not test(testnet) 
    & not test(regtest) 
    & not test(client_rpcs)

    & not (binary_id(integration-tests::state_service) and test(zebrad::check_info::regtest_no_cache))
    & not (binary_id(integration-tests::state_service) and test(zebrad::get::address_balance_regtest))
    & not (binary_id(integration-tests::state_service) and test(zebrad::get::address_tx_ids_regtest))
    & not (binary_id(integration-tests::state_service) and test(zebrad::get::address_utxos))
    & not (binary_id(integration-tests::state_service) and test(zebrad::get::block_count))
    & not (binary_id(integration-tests::state_service) and test(zebrad::get::block_object_regtest))
    & not (binary_id(integration-tests::state_service) and test(zebrad::get::block_raw_regtest))
    & not (binary_id(integration-tests::state_service) and test(zebrad::get::raw_mempool_regtest))
    & not (binary_id(integration-tests::state_service) and test(zebrad::get::raw_transaction_regtest))
    & not (binary_id(integration-tests::state_service) and test(zebrad::get::z::subtrees_by_index_regtest))
    & not (binary_id(integration-tests::state_service) and test(zebrad::get::z::treestate_regtest))
    & not (binary_id(integration-tests::state_service) and test(zebrad::lightwallet_indexer::get_address_utxos))
    & not (binary_id(integration-tests::state_service) and test(zebrad::lightwallet_indexer::get_address_utxos_stream))
    & not (binary_id(integration-tests::state_service) and test(zebrad::lightwallet_indexer::get_block))
    & not (binary_id(integration-tests::state_service) and test(zebrad::lightwallet_indexer::get_block_range_full))
    & not (binary_id(integration-tests::state_service) and test(zebrad::lightwallet_indexer::get_block_range_nullifiers))
    & not (binary_id(integration-tests::state_service) and test(zebrad::lightwallet_indexer::get_latest_block))
    & not (binary_id(integration-tests::state_service) and test(zebrad::lightwallet_indexer::get_latest_tree_state))
    & not (binary_id(integration-tests::state_service) and test(zebrad::lightwallet_indexer::get_subtree_roots))
    & not (binary_id(integration-tests::state_service) and test(zebrad::lightwallet_indexer::get_taddress_balance))
    & not (binary_id(integration-tests::state_service) and test(zebrad::lightwallet_indexer::get_taddress_txids))
    & not (binary_id(integration-tests::state_service) and test(zebrad::lightwallet_indexer::get_transaction))
    & not (binary_id(integration-tests::state_service) and test(zebrad::lightwallet_indexer::get_tree_state))
    & not (binary_id(integration-tests::wallet_to_validator) and test(zebrad::state_service::connect_to_node_get_info))
    & not (binary_id(integration-tests::wallet_to_validator) and test(zebrad::state_service::monitor_unverified_mempool))
    & not (binary_id(integration-tests::wallet_to_validator) and test(zebrad::state_service::send_to::all))
    & not (binary_id(integration-tests::wallet_to_validator) and test(zebrad::state_service::send_to::orchard))
    & not (binary_id(integration-tests::wallet_to_validator) and test(zebrad::state_service::send_to::sapling))
    & not (binary_id(integration-tests::wallet_to_validator) and test(zebrad::state_service::send_to::transparent))
    & not (binary_id(integration-tests::wallet_to_validator) and test(zebrad::state_service::shield))
    & not (binary_id(zaino-testutils) and test(launch_testmanager::zebrad::state_service::zaino))
    & not (binary_id(zaino-testutils) and test(launch_testmanager::zebrad::state_service::zaino_clients))
"""

[profile.ci.junit]  # this can be some other profile, too
path = "junit.xml"
