//! Per-capability error types.
//!
//! Distinct types (not one god-enum) so each outer client maps precisely, and
//! so capabilities can diverge later — the CLAUDE.md "per-conversion error
//! granularity" rule, applied to the driving surface. In this scaffold they
//! share a shape; a macro keeps them DRY (a `fn` cannot define types).

use crate::Capability;
use zaino_primitives::types::{BlockHash, Height, TransparentAddress, TransparentInput};

/// Every read-boundary failure separates a *not-yet-serviceable* answer and a
/// *domain* "not found" (which is `Ok(None)`, never an error) from real backend
/// failure classified transient/fatal (the PR's *Transient failure* glossary).
macro_rules! read_error {
    ($(#[$m:meta])* $name:ident) => {
        $(#[$m])*
        #[derive(Debug, thiserror::Error)]
        pub enum $name {
            /// Backing index not built to the requested height yet.
            #[error("not serviceable yet: {0:?}")]
            NotServiceable(Capability),
            /// Likely to resolve on retry (e.g. a mid-swap reorg race).
            #[error("transient read failure: {0}")]
            Transient(String),
            /// Unrecoverable backend failure.
            #[error("fatal read failure: {0}")]
            Fatal(String),
        }

        impl $name {
            /// True only for the not-yet-serviceable stub — the read's backing
            /// substrate is unwired, distinct from a real backend failure
            /// (`Transient` / `Fatal`) or a domain miss (`Ok(None)`). The
            /// conformance kit asserts this is false across a use case's read-set:
            /// a served capability may answer, miss, or fail, but never report
            /// itself unserviceable.
            pub fn is_not_serviceable(&self) -> bool {
                matches!(self, Self::NotServiceable(_))
            }
        }
    };
}

read_error!(/// Errors from [`crate::BlockRead`].
    BlockReadError);
read_error!(/// Errors from [`crate::TransactionRead`].
    TxReadError);
read_error!(/// Errors from [`crate::TreestateRead`].
    TreestateReadError);
/// Errors from [`crate::AddressRead`].
///
/// Hand-written rather than generated by `read_error!`, because address reads
/// alone can meet a validator that does not implement the method: the
/// insight-explorer `getaddress*` family is a zcashd extension a zebra backend
/// answers with JSON-RPC method-not-found. That case is [`Unsupported`], which
/// the node-RPC adapter renders as method-not-found (`-32601`) rather than an
/// internal error — truthful about whose gap it is. The other three cases match
/// the macro's shape.
#[derive(Debug, thiserror::Error)]
pub enum AddressReadError {
    /// Backing index not built to the requested height yet.
    #[error("not serviceable yet: {0:?}")]
    NotServiceable(Capability),
    /// The backing validator does not implement this address method.
    #[error("address method unsupported by the validator: {0}")]
    Unsupported(String),
    /// The address has more history than the per-request ceiling allows, so
    /// serving it would fan a single read out past its bound — a policy refusal,
    /// not a backend failure: the request is well-formed and the index healthy.
    /// Distinct from [`Fatal`](Self::Fatal) (a real read failure) and
    /// [`Transient`](Self::Transient) (a retryable race); retrying is futile until
    /// a balance/UTXO-by-address aggregate lifts the ceiling. It bounds a single
    /// request so a pathological (pool-scale) address fails alone rather than
    /// exhausting memory for the whole process. Mirrors
    /// [`TransactionViewError::PrevoutFanoutTooLarge`].
    #[error("address {address} has more than {limit} entries in the requested range")]
    TooLarge {
        /// The address whose history exceeded the ceiling.
        address: TransparentAddress,
        /// The per-request ceiling that was exceeded.
        limit: usize,
    },
    /// Likely to resolve on retry (e.g. a mid-swap reorg race).
    #[error("transient read failure: {0}")]
    Transient(String),
    /// Unrecoverable backend failure.
    #[error("fatal read failure: {0}")]
    Fatal(String),
}

impl AddressReadError {
    /// True only for the not-yet-serviceable stub — see the macro's doc.
    pub fn is_not_serviceable(&self) -> bool {
        matches!(self, Self::NotServiceable(_))
    }
}

read_error!(/// Errors from [`crate::SpendRead`].
    SpendReadError);
read_error!(/// Errors from [`crate::MempoolContent`].
    MempoolReadError);
read_error!(/// Generic read error for streamed surfaces and [`crate::ForkReconcile`].
    ReadError);

/// A [`BlockReadError`] folds into the generic [`ReadError`] 1:1 — same three
/// cases. A per-height block read ([`crate::BlockRead::block`]) fails with
/// [`BlockReadError`], while the streamed read ([`crate::BlockRead::stream_blocks`])
/// yields [`ReadError`], so a per-height failure lifts into the stream's error
/// with no reclassification. Context-free, so `From` is the right tool: the
/// named-method boundary rule governs `Persistent*`/`proto::` conversions, not
/// two business error types.
impl From<BlockReadError> for ReadError {
    fn from(error: BlockReadError) -> Self {
        match error {
            BlockReadError::NotServiceable(capability) => Self::NotServiceable(capability),
            BlockReadError::Transient(message) => Self::Transient(message),
            BlockReadError::Fatal(message) => Self::Fatal(message),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{BlockReadError, ReadError};
    use crate::Capability;

    #[test]
    fn block_read_error_lifts_into_read_error_by_variant() {
        assert!(matches!(
            ReadError::from(BlockReadError::NotServiceable(Capability::Blocks)),
            ReadError::NotServiceable(Capability::Blocks)
        ));
        assert!(matches!(
            ReadError::from(BlockReadError::Transient("race".to_owned())),
            ReadError::Transient(message) if message == "race"
        ));
        assert!(matches!(
            ReadError::from(BlockReadError::Fatal("corrupt".to_owned())),
            ReadError::Fatal(message) if message == "corrupt"
        ));
    }
}

/// Errors from [`crate::BlockHashRead`].
///
/// A typed enum, not a `read_error!` String type: the timestamp-range search has
/// a failure mode the shared three-case shape cannot name — a hole in the chain
/// view, where a header the search needed at or below the pinned tip is missing.
/// A range beyond the tip or before genesis is a domain answer (an empty list,
/// never a variant here). The tier-read variant keeps its cause with
/// `#[source]`, so an operator reaches the concrete backend failure.
#[derive(Debug, thiserror::Error)]
pub enum BlockHashReadError {
    /// A header the search needed, at a height at or below the pinned tip, was
    /// missing — a hole in the chain view. The search requests only heights
    /// where a block must exist, so a missing one is a view inconsistency,
    /// surfaced loud rather than silently dropping a block that might be in
    /// range. Mirrors the consensus search's own missing-header failure.
    #[error("missing header at height {height} during the block-hash timestamp search")]
    MissingHeader {
        /// The height whose header the chain view reported as absent.
        height: Height,
    },
    /// A tier read failed while reading a header during the search.
    #[error("tier read failed during the block-hash timestamp search")]
    TierRead {
        /// The tier read failure, kept as the source chain.
        #[source]
        source: BlockReadError,
    },
}

/// A tier read failure during the search folds into the tier-read variant,
/// keeping its cause — the `?` in the engine's drive loop (`view.header(h)?`)
/// lifts a [`BlockReadError`] straight into [`BlockHashReadError`].
impl From<BlockReadError> for BlockHashReadError {
    fn from(source: BlockReadError) -> Self {
        Self::TierRead { source }
    }
}

/// Failure to *acquire* a snapshot — the one reorg race ADR-0003 admits.
/// Reads *through* a snapshot never race, so they never yield this.
#[derive(Debug, thiserror::Error)]
#[error("could not acquire a snapshot: {0}")]
pub struct Transient(pub String);

/// A broadcast rejection is a *domain answer*, not a backend failure.
#[derive(Debug, thiserror::Error)]
pub enum BroadcastRejection {
    /// Bytes did not decode to a transaction.
    #[error("malformed transaction: {0}")]
    Malformed(String),
    /// Decoded, but consensus/validation rejected it (with the engine's reason).
    #[error("transaction rejected: {0}")]
    Invalid(String),
}

/// Errors from [`crate::TransactionViewRead`].
///
/// A typed enum, not a `read_error!` String type: resolving a transparent input
/// to the output it spends has failure modes the shared three-case shape cannot
/// name. A miss on the *requested* transaction or block is a domain answer
/// (`Ok(None)`, never a variant here); the variants are the inconsistencies and
/// transport failures that can arise while resolving the inputs of a transaction
/// the validator *did* serve. The transport variant keeps its cause with
/// `#[source]`, so an operator walking the chain reaches the concrete failure.
#[derive(Debug, thiserror::Error)]
pub enum TransactionViewError {
    /// The validator could not be reached or answered unusably.
    #[error("validator unavailable")]
    Unavailable {
        /// The transport failure, kept as the source chain.
        #[source]
        cause: Box<dyn std::error::Error + Send + Sync>,
    },
    /// The validator served a spending transaction but not the transaction it
    /// spends — a source inconsistency, named rather than rendered as a blank
    /// input value.
    #[error("prevout {outpoint:?} is unknown to the validator")]
    MissingPrevout {
        /// The input whose referenced output could not be found.
        outpoint: TransparentInput,
    },
    /// Resolving this request would fetch more distinct prevout transactions than
    /// the passthrough-phase ceiling allows — a policy refusal, not a transport
    /// failure: the request is well-formed and the validator healthy, but serving
    /// it by per-prevout passthrough would fan out beyond the bound. Distinct from
    /// [`Unavailable`](Self::Unavailable), which is a validator that could not be
    /// reached. A local outpoint index removes the fetch and lifts this ceiling.
    #[error(
        "resolving this request needs {needed} prevout fetches, over the per-request ceiling of {ceiling}"
    )]
    PrevoutFanoutTooLarge {
        /// The number of distinct external prevout transactions the request would
        /// fetch.
        needed: usize,
        /// The per-request ceiling that was exceeded.
        ceiling: usize,
    },
    /// The spent transaction exists but has no output at the referenced index.
    #[error("prevout {outpoint:?} names output {index} of a transaction with {outputs} outputs")]
    PrevoutIndexOutOfRange {
        /// The input whose referenced output index is out of range.
        outpoint: TransparentInput,
        /// The referenced output index.
        index: u32,
        /// The number of outputs the spent transaction actually has.
        outputs: usize,
    },
}

/// Errors from [`crate::BlockDeltasRead`].
///
/// A typed enum, not a `read_error!` String type: composing a block's deltas has
/// failure modes the shared three-case shape cannot name. An unknown block is a
/// domain answer (`Ok(None)`, never a variant here); the variants are the
/// inconsistencies that arise while composing a block the reads *did* serve.
/// Each keeps its cause with `#[source]`, so an operator reaches the concrete
/// failure. `getblockdeltas` is composed over reads the node-RPC set already
/// holds, so these are the only ways composition fails.
#[derive(Debug, thiserror::Error)]
pub enum BlockDeltasError {
    /// Resolving the block's transactions to the outputs their inputs spend
    /// failed — a transport failure, a prevout the validator could not serve, or
    /// a fan-out past the passthrough ceiling (see [`TransactionViewError`]).
    #[error("resolving the block's transparent inputs failed")]
    TransactionView(#[source] TransactionViewError),
    /// Reading the block, its chain position, or a predecessor header failed.
    #[error("reading the block or its chain position failed")]
    Block(#[source] BlockReadError),
    /// A predecessor header the median-time-past needed, at or below the pinned
    /// tip, was missing — a hole in the chain view. The median time is taken over
    /// heights that must exist, so a missing one is a view inconsistency,
    /// surfaced loud rather than inventing a median. Mirrors
    /// [`BlockHashReadError::MissingHeader`].
    #[error("missing header at height {height} while composing the block's median time")]
    MissingHeader {
        /// The height whose header the chain view reported as absent.
        height: Height,
    },
    /// A resolved input value could not be represented as a negative value
    /// movement — a magnitude past the money supply. Fails loud rather than
    /// truncating a corrupt amount.
    #[error("input value {value} is not a representable negative delta")]
    InputValueOutOfRange {
        /// The input value that could not be negated within the supply bound.
        value: u64,
    },
    /// The requested block is not on the main chain. zcashd's `blockToDeltasJSON`
    /// reports confirmations only for a main-chain block and throws otherwise; the
    /// composed read detects the same condition from the passthrough verbose
    /// block's negative confirmations (`-1` off-chain) and declines rather than
    /// emitting a delta view for an orphan. The adapter maps it to zcashd's exact
    /// `-5` error.
    #[error("block {hash} is an orphan (not on the main chain)")]
    Orphan {
        /// The hash of the off-chain block.
        hash: BlockHash,
    },
}

/// A transaction-view resolution failure folds into the composed-read variant,
/// keeping its cause — the `?` on `block_transaction_views` lifts a
/// [`TransactionViewError`] straight into [`BlockDeltasError`].
impl From<TransactionViewError> for BlockDeltasError {
    fn from(source: TransactionViewError) -> Self {
        Self::TransactionView(source)
    }
}

/// A block / verbose / header read failure folds into the composed-read variant,
/// keeping its cause — the `?` on the block, chain-position and header reads lifts
/// a [`BlockReadError`] straight into [`BlockDeltasError`].
impl From<BlockReadError> for BlockDeltasError {
    fn from(source: BlockReadError) -> Self {
        Self::Block(source)
    }
}
