[package]
name = "zaino-commons"
description = "Common types and configurations shared across Zaino crates."
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
# Infra
zingo-infra-services = { workspace = true }

# Zebra
zebra-chain = { workspace = true }
zebra-state = { workspace = true }

# Miscellaneous Workspace
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["time", "fs"] }
tonic = { workspace = true }
reqwest = { workspace = true }
humantime-serde = "1.1"
base64 = "0.22"
thiserror = "1.0"
