[workspace]

[package]
name = "integration-tests"
description = "Crate containing Zaino's integration-tests."
publish = false

authors = ["Zingo Lab Cyan"]
repository = "https://github.com/zingolabs"
homepage = "https://www.zingolabs.org/"
edition = "2021"
license = "Apache-2.0"
version = "0.2.0"

[features]
# **Experimental and alpha features**
# Exposes the **complete** set of experimental / alpha features currently implemented in Zaino.
experimental_features = ["transparent_address_history_experimental"]

# Activates transparent address history capability in zaino
#
# NOTE: currently this is only implemented in the finalised state.
transparent_address_history_experimental = [
    "zaino-state/transparent_address_history_experimental",
    "zainod/transparent_address_history_experimental",
    "zaino-testutils/transparent_address_history_experimental"
]

[dev-dependencies]
anyhow = "1.0"

# Test utility
zainod = { path = "../zainod" }
zaino-testutils = { path = "../zaino-testutils" }
zaino-fetch = { path = "../zaino-fetch" }
zaino-proto = { path = "../zaino-proto" }
zaino-common = { path = "../zaino-common" }
wire_serialized_transaction_test_data = "1.0.0"
zaino-state = { path = "../zaino-state", features = ["test_dependencies"] }
zebra-chain = "6.0.1"
zebra-state = "5.0.0"
zebra-rpc = "6.0.1"
zip32 = "0.2.1"

core2 = "0.4"
serde_json = { version = "1.0", features = ["preserve_order"] }
futures = "0.3.30"
tempfile = "3.2"
tower = { version = "0.4", features = ["buffer", "util"] }
hex = "0.4"

# Runtime
tokio = { version = "1.38", features = ["full"] }

# Zingo-infra
zcash_local_net = { git = "https://github.com/zingolabs/infrastructure.git", rev = "1a75152f4744b9e130a7d7f249a5b7691a6bf2fe" }

[profile.test]
opt-level = 3
debug = true
