//! The client a consumer holds to talk to a validator.
//!
//! `ValidatorClient<V>` wraps a single-attempt adapter `V` and *is* the thing
//! the rest of Zaino queries the chain through. Resilience is what it does, not
//! what it is: it answers the canonical query ports, retrying transient
//! transport failures against the adapter so a consumer never has to.
//!
//! ```ignore
//! let adapter = ZebraRpcAdapter::new(rpc);
//! let source = ValidatorClient::new(adapter, RetryPolicy::default());
//! let block = source.get_block(height).await?; // → SourceError, retries handled
//! ```
//!
//! # The canonical ports are the resilient ones
//!
//! `ValidatorClient<V>` implements the **canonical** query ports ([`GetBlock`](crate::GetBlock),
//! [`GetChainTip`](crate::GetChainTip), …) — the unqualified names — for any `V`
//! implementing the matching single-attempt [`OneShot*`](crate::OneShotGetBlock)
//! port. Those canonical ports return [`SourceError`], whose
//! [`Unavailable`](SourceError::Unavailable) variant is "retried and gave up", so
//! a consumer binding a canonical port knows in the types that transience is
//! already handled below it. The impls are generated by
//! [`#[resilient_port]`](zaino_source_macros::resilient_port) on each `OneShot*`
//! trait, so the delegation and the [`QueryError`] → [`SourceError`] translation
//! live only here, in [`with_retry`](ValidatorClient::with_retry).
//!
//! # The resilient ports are sealed
//!
//! Every canonical port has [`sealed::Sealed`] as a supertrait, and the only
//! implementor of `Sealed` is `ValidatorClient<V>`. A value satisfying a canonical
//! port has therefore provably been through the retry ladder — a consumer
//! cannot hand-roll a type that claims resilience without retrying.

use std::future::Future;
use std::time::Duration;

use crate::error::{FailureMode, QueryError, SourceError, UnavailableError};

/// Seals the canonical (resilient) ports so only [`ValidatorClient`] can implement
/// them.
///
/// Each canonical port names `Sealed` as a supertrait; `Sealed` is implemented
/// only for [`ValidatorClient<V>`], so "holds a resilient port" is a proof the value
/// went through [`ValidatorClient::with_retry`], not a claim a consumer can fake.
///
/// # If the compiler sent you here because you wanted your own retrying
///
/// You tried to implement a canonical port and the seal stopped you. That is
/// deliberate, but it is not a dead end — "roll your own retry" is really three
/// different asks, and only the last one needs this seal to move:
///
/// - **Different tuning** — more attempts, longer backoff, a different delay
///   curve. You need no new type at all: hand [`ValidatorClient::new`] a custom
///   [`RetryPolicy`]. The seal was never in your way here; this is the common
///   case, so reach for it before anything below.
/// - **Different classification** — which failures are worth retrying. That
///   decision lives in exactly one place, the `is_retryable` function in this
///   module. A PR extending it is small and welcome; prefer teaching it through
///   [`RetryPolicy`] so the choice stays configuration rather than a fork.
/// - **A structurally different strategy** — circuit breaking, hedged requests,
///   failover across several validators — something no policy can express. This
///   is the only case the seal actually blocks, and on purpose: such a type
///   could *claim* a resilient port while quietly not honoring the retry
///   contract. Open an issue to unseal (or to widen this seal to a sanctioned
///   set). Unsealing is a small, non-breaking change; it is held back only until
///   a real second strategy exists to justify trading the compile-time proof for
///   a documented contract — at which point the tests in this module become the
///   conformance kit that contract is checked against.
pub(crate) mod sealed {
    /// Implemented only for [`ValidatorClient`](super::ValidatorClient).
    pub trait Sealed {}
    impl<V> Sealed for super::ValidatorClient<V> {}
}

/// Retry policy configuration.
#[derive(Debug, Clone)]
pub struct RetryPolicy {
    /// Maximum number of attempts (including the first).
    pub max_attempts: u32,
    /// Initial delay between retries.
    pub initial_delay: Duration,
    /// Multiply delay by this factor after each retry.
    pub backoff_factor: f64,
    /// Maximum delay between retries.
    pub max_delay: Duration,
}

impl Default for RetryPolicy {
    fn default() -> Self {
        Self {
            max_attempts: 3,
            initial_delay: Duration::from_millis(250),
            backoff_factor: 2.0,
            max_delay: Duration::from_secs(8),
        }
    }
}

impl RetryPolicy {
    fn delay_for(&self, attempt: u32) -> Duration {
        if attempt <= 1 {
            return self.initial_delay;
        }
        let exponent = (attempt - 1).min(30);
        let factor = self.backoff_factor.powi(exponent as i32);
        let millis = (self.initial_delay.as_millis() as f64 * factor) as u64;
        Duration::from_millis(millis).min(self.max_delay)
    }
}

/// The validator's work queue is full — it is up, but busy.
const WORK_QUEUE_FULL: i64 = -1;

/// The validator is still warming up and not yet serving.
///
/// A transient startup condition, not a rejection: it ends on its own once the
/// node finishes loading. Retrying is the only correct response — failing
/// immediately makes a validator that is merely slow to start look permanently
/// broken to everything downstream.
const IN_WARMUP: i64 = -28;

/// Whether a transport error kind is worth retrying.
fn is_retryable(kind: &FailureMode) -> bool {
    match kind {
        FailureMode::Connection => true,
        FailureMode::Timeout => true,
        FailureMode::HttpStatus(code) => *code >= 500,
        // Everything else the validator answers with a code is its considered
        // reply, and asking again will produce the same one.
        FailureMode::RpcError(code) => *code == WORK_QUEUE_FULL || *code == IN_WARMUP,
        FailureMode::Parse => false,
        FailureMode::Auth => false,
    }
}

/// Resilience wrapper around any source adapter.
///
/// Implements the canonical (resilient) query ports for any `V` implementing
/// the matching `OneShot*` ports; the impls are generated by
/// [`#[resilient_port]`](zaino_source_macros::resilient_port) and all funnel
/// through [`with_retry`](Self::with_retry).
pub struct ValidatorClient<V> {
    inner: V,
    policy: RetryPolicy,
}

impl<V> ValidatorClient<V> {
    /// Wrap an adapter with a retry policy.
    pub fn new(inner: V, policy: RetryPolicy) -> Self {
        Self { inner, policy }
    }

    /// The wrapped adapter, for the generated port impls to delegate to.
    pub(crate) fn inner(&self) -> &V {
        &self.inner
    }

    /// Core retry loop. Every generated port method delegates here.
    pub(crate) async fn with_retry<T, E, F, Fut>(&self, mut f: F) -> Result<T, SourceError<E>>
    where
        E: core::fmt::Debug + core::fmt::Display,
        F: FnMut() -> Fut,
        Fut: Future<Output = Result<T, QueryError<E>>>,
    {
        let mut attempt = 0u32;

        loop {
            attempt += 1;

            match f().await {
                Ok(value) => return Ok(value),

                Err(QueryError::Domain(e)) => return Err(SourceError::Domain(e)),

                Err(QueryError::Fetch(e)) => {
                    if !is_retryable(&e.mode) || attempt >= self.policy.max_attempts {
                        if is_retryable(&e.mode) {
                            return Err(SourceError::Unavailable(UnavailableError {
                                attempts: attempt,
                                last_error: e,
                            }));
                        }
                        return Err(SourceError::Fetch(e));
                    }

                    tokio::time::sleep(self.policy.delay_for(attempt)).await;
                }
            }
        }
    }
}

// The canonical (resilient) port impls for `ValidatorClient<V>` are generated by
// `#[resilient_port]` on each `OneShot*` trait (see e.g. `get_block.rs`).

// Subscriptions are forwarded unchanged — there is nothing to retry here, and
// that is a property of the signature, not a shortcut. `subscribe_to_*` is
// synchronous and returns `Option<Receiver>`, not `Result`: it hands back a
// channel handle without reaching the validator, so `None` means "no push path"
// (a permanent capability fact), never "transiently could not subscribe."
//
// Transient unreachability *is* retried, at the boundary where the fallible
// round-trip actually happens: the wake carries no data, so the consumer then
// fetches through the resilient query ports (`get_chain_tip`, `get_block`, …),
// which retry — and if the validator is down the wake simply never fires and the
// consumer's poll-interval fallback calls those same resilient ports. Retrying
// the handout would only delay learning there is no push path.
impl<V: crate::SubscribeBlocks> crate::SubscribeBlocks for ValidatorClient<V> {
    fn subscribe_to_blocks_received(&self) -> Option<tokio::sync::watch::Receiver<()>> {
        self.inner.subscribe_to_blocks_received()
    }
}

impl<V: crate::SubscribeChainTip> crate::SubscribeChainTip for ValidatorClient<V> {
    fn subscribe_to_chain_tip(
        &self,
    ) -> Option<tokio::sync::watch::Receiver<crate::TipObservation>> {
        self.inner.subscribe_to_chain_tip()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `ValidatorClient<V>` provides the canonical (resilient) ports for any `V` that
    /// provides the matching `OneShot*` ports. A compile-time check: if
    /// `#[resilient_port]` stopped generating an impl, or the seal shut
    /// `ValidatorClient` out of its own port, this stops building.
    #[test]
    fn resilient_provides_the_query_ports() {
        fn assert_bound<S>()
        where
            S: crate::GetBlock + crate::GetBlockByHash + crate::GetChainTip + crate::GetTreestate,
        {
        }
        assert_bound::<ValidatorClient<crate::mock::MockChain>>();
    }

    // ---------------------------------------------------------------
    // Unit tests: classification + backoff
    // ---------------------------------------------------------------

    #[test]
    fn connection_is_retryable() {
        assert!(is_retryable(&FailureMode::Connection));
    }

    #[test]
    fn timeout_is_retryable() {
        assert!(is_retryable(&FailureMode::Timeout));
    }

    #[test]
    fn http_500_is_retryable() {
        assert!(is_retryable(&FailureMode::HttpStatus(500)));
        assert!(is_retryable(&FailureMode::HttpStatus(503)));
    }

    #[test]
    fn http_400_is_not_retryable() {
        assert!(!is_retryable(&FailureMode::HttpStatus(400)));
        assert!(!is_retryable(&FailureMode::HttpStatus(404)));
    }

    #[test]
    fn work_queue_full_is_retryable() {
        assert!(is_retryable(&FailureMode::RpcError(-1)));
    }

    /// A warming-up validator is starting, not broken. Failing immediately here
    /// makes a slow start look like a permanent fault to every consumer.
    #[test]
    fn in_warmup_is_retryable() {
        assert!(is_retryable(&FailureMode::RpcError(-28)));
    }

    #[test]
    fn block_not_found_rpc_is_not_retryable() {
        assert!(!is_retryable(&FailureMode::RpcError(-8)));
    }

    #[test]
    fn parse_is_not_retryable() {
        assert!(!is_retryable(&FailureMode::Parse));
    }

    #[test]
    fn auth_is_not_retryable() {
        assert!(!is_retryable(&FailureMode::Auth));
    }

    #[test]
    fn delay_exponential_backoff() {
        let policy = RetryPolicy {
            initial_delay: Duration::from_millis(100),
            backoff_factor: 2.0,
            max_delay: Duration::from_secs(10),
            ..Default::default()
        };
        assert_eq!(policy.delay_for(1), Duration::from_millis(100));
        assert_eq!(policy.delay_for(2), Duration::from_millis(200));
        assert_eq!(policy.delay_for(3), Duration::from_millis(400));
    }

    #[test]
    fn delay_capped_at_max() {
        let policy = RetryPolicy {
            initial_delay: Duration::from_secs(1),
            backoff_factor: 10.0,
            max_delay: Duration::from_secs(5),
            ..Default::default()
        };
        assert_eq!(policy.delay_for(3), Duration::from_secs(5));
    }

    // ---------------------------------------------------------------
    // Integration tests: ValidatorClient<MockChain> with failure injection
    // ---------------------------------------------------------------

    // The mock is compiled for this crate's own tests as well as behind the
    // `testing` feature, so these need no gate of their own.
    mod integration {
        use super::*;
        use crate::mock::MockChain;
        // The resilient ports whose generated impls these tests exercise.
        use crate::{GetBlock, GetChainTip};
        use zaino_primitives::types::{
            Block, BlockHash, BlockHeader, ChainMetadata, EquihashSolution, Height, TreeSize,
        };

        fn height(h: u32) -> Height {
            Height::try_from(h).expect("valid")
        }

        fn hash(b: u8) -> BlockHash {
            BlockHash::from([b; 32])
        }

        fn test_block(h: u32, hash_byte: u8) -> Block {
            Block {
                header: BlockHeader {
                    hash: hash(hash_byte),
                    version: 4,
                    prev_hash: BlockHash::ZERO,
                    height: height(h),
                    time: 0,
                    merkle_root: [0; 32].into(),
                    block_commitments: [0; 32].into(),
                    bits: 0,
                    nonce: [0; 32],
                    solution: EquihashSolution::Regtest([0; 36]),
                },
                transactions: vec![],
                chain_metadata: ChainMetadata {
                    sapling_tree_size: TreeSize::ZERO,
                    orchard_tree_size: TreeSize::ZERO,
                    ironwood_tree_size: TreeSize::ZERO,
                },
            }
        }

        fn fast_policy(max_attempts: u32) -> RetryPolicy {
            RetryPolicy {
                max_attempts,
                initial_delay: Duration::from_millis(1),
                backoff_factor: 1.0,
                max_delay: Duration::from_millis(1),
            }
        }

        #[tokio::test]
        async fn retries_transient_then_succeeds() {
            let mock = MockChain::new()
                .with_block(test_block(0, 1))
                .fail_next(2, FailureMode::Timeout);

            let source = ValidatorClient::new(mock, fast_policy(5));

            let block = source.get_block(height(0)).await.expect("succeeds");
            assert_eq!(block.header.hash, hash(1));
        }

        #[tokio::test]
        async fn exhausts_retries_returns_unavailable() {
            let mock = MockChain::new()
                .with_block(test_block(0, 1))
                .fail_next(10, FailureMode::Connection);

            let source = ValidatorClient::new(mock, fast_policy(3));

            let err = source.get_block(height(0)).await.unwrap_err();
            assert!(
                matches!(err, SourceError::Unavailable(ref u) if u.attempts == 3),
                "expected Unavailable after 3 attempts, got: {err:?}"
            );
        }

        #[tokio::test]
        async fn fatal_error_not_retried() {
            let mock = MockChain::new()
                .with_block(test_block(0, 1))
                .fail_next(1, FailureMode::Auth);

            let source = ValidatorClient::new(mock, fast_policy(5));

            let err = source.get_block(height(0)).await.unwrap_err();
            assert!(
                matches!(err, SourceError::Fetch(ref e) if e.mode == FailureMode::Auth),
                "expected Fetch(Auth), got: {err:?}"
            );
        }

        #[tokio::test]
        async fn domain_error_not_retried() {
            let mock = MockChain::new();

            let source = ValidatorClient::new(mock, fast_policy(5));

            let err = source.get_block(height(99)).await.unwrap_err();
            assert!(
                matches!(err, SourceError::Domain(_)),
                "expected Domain, got: {err:?}"
            );
        }

        #[tokio::test]
        async fn chain_tip_retries_transient() {
            let mock = MockChain::new()
                .with_block(test_block(0, 1))
                .fail_next(1, FailureMode::Timeout);

            let source = ValidatorClient::new(mock, fast_policy(3));

            let (tip_hash, tip_height) = source.get_chain_tip().await.expect("succeeds");
            assert_eq!(tip_hash, hash(1));
            assert_eq!(tip_height, height(0));
        }
    }
}
