name: Cargo checkmate

on: [workflow_call]

jobs:
  cargo-checkmate:
    name: Cargo checkmate
    strategy:
      matrix:
        phase: [check, clippy, doc, format]
    # needs: cache-checkmate
    runs-on: ziserv-2
    # if: github.event.pull_request.draft == false
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - name: cargo checkmate
        uses: cargo-checkmate/action@main
        with:
          phase: ${{ matrix.phase }}

