name: Check MinIO Connection

on:
  push:
  workflow_dispatch:

jobs:
  check-minio:
    runs-on: ziserv-2
    env:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      S3_ENDPOINT: https://minio.gh-cache.svc.cluster.local
    steps:

    - name: Test connection to MinIO
      run: |
        echo "Testing connection to MinIO server..."
        curl -k -X GET "${{ env.S3_ENDPOINT }}/minio/health/live" --user ${{ env.AWS_ACCESS_KEY_ID }}:${{ env.AWS_SECRET_ACESS_KEY }}
